name: Deploy to wp org

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Fix apt metadata change issue
        run: sudo apt-get update --allow-releaseinfo-change

      - name: Install SVN
        run: sudo apt-get install -y subversion

      - name: Setup composer
        run: composer setup

      - name: Setup Node.js 22.16.0
        uses: actions/setup-node@v2
        with:
          node-version: "22.16.0"

      # Cache node_modules
      - name: Cache Node.js dependencies
        if: always()
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install pnpm globally
        run: npm install -g pnpm@latest-10

      - name: Install pnpm dependencies
        run: pnpm install

      - name: Compile Scripts
        run: pnpm minify

      - name: Fix Text Domain
        run: pnpm fixtextdomain

      - name: Generate Text Domain POT file
        run: composer make-production-pot

      - name: Remove Composer Dev Dependencies
        run: composer build

      - name: Build plugin
        run: pnpm git-compress

      - name: Deploy to wp org
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: formgent
          BUILD_DIR: formgent

      - name: Create zip file
        run: |
          tag_name=$(git describe --tags --abbrev=0)
          zip -r "formgent.${tag_name}.zip" formgent

      - name: Upload zip file as a release asset
        uses: softprops/action-gh-release@v1
        with:
          files: formgent*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
